#!/usr/bin/env python3.6

import argparse
import sys

def password_search():

    parser = argparse.ArgumentParser(description = "passwordsearcher")
    parser.add_argument('filename',help='mention the file name and directory')
    parser.add_argument('search',help = 'enter a string that you want to find in the wordlist')

    result = parser.parse_args()
    search = result.search
    #print(result)

    try:
        f = open(sys.argv[1],'r')

    except:
        print(f"Error 404 file not found")
        sys.exit(2)
    else:

        with f:

            passread = f.readlines()

            for word in passread:


                if search == word.strip():
                    return search



if __name__ == "__main__":


    a = password_search()

    if  a!= None:
        print(f"\n\nPassword Found!!!!! {a}\n\n")
    else:
        print(f"\n\nPassword not Found\n\n")


